name: container-images


on:
  push:
    branches: [ "*" ]
    tags: [ "v*" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: docker/setup-qemu-action@v1
    - uses: docker/setup-buildx-action@v1

    #
    - run: echo "IMAGE_TAG=dev" >> $GITHUB_ENV
      if: github.ref_name == 'main'
    - run: echo "IMAGE_TAG=${GITHUB_REF_NAME}" >> $GITHUB_ENV
      if: github.ref_name != 'main' && startsWith(github.ref, 'refs/heads/')
    - run: echo "IMAGE_TAG=${GITHUB_REF##*/}" >> $GITHUB_ENV
      if: startsWith(github.ref, 'refs/tags/v')
    #

    - name: Login to ghcr.io
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Login to docker.io
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_UID }}
        password: ${{ secrets.DOCKER_HUB_PAT }}

    - name: Build and push default image
      uses: docker/build-push-action@v3.2.0
      with:
        context: images/polygond/heimdall # https://stackoverflow.com/a/71159809/11276254
        push: true
        tags: |
          ghcr.io/${{ github.repository }}/go-songbird:${{ env.IMAGE_TAG }}
        #  ${{ secrets.DOCKER_HUB_REPO_HEIMDALL }}:${{ env.IMAGE_TAG }}